/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concurrency.study;

import concurrency.study.collection.CollectionDemo;
import concurrency.study.semaphore.SemaphoreDemo;
import concurrency.study.threadPool.ThreadPoolDemo;

public class App {

    public static void main(String[] args) throws InterruptedException {

        // semaphore demo
        new SemaphoreDemo().run();

        // thread pool
        new ThreadPoolDemo().run();

        // Collections
        new CollectionDemo().run();
    }
}
