/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concurrency.study;

import concurrency.study.semaphore.SemaphoreDemo;

public class App {

    public static void main(String[] args) throws InterruptedException {

        // semaphore demo
        new SemaphoreDemo().run();
    }
}
